media:
  input: public/images
  output: /images
content:
  - name: landing
    label: Landing
    type: file
    path: src/landing.md
    fields:
      - name: title
        type: text
        label: Title
        required: true
      - name: subtitle
        type: text
        label: Subtitle
        required: true
      - name: content
        type: rich-text
        label: Content
        required: true
      - name: mapUrl
        type: text
        label: Map URL
        required: true
      - name: maps
        type: image
        label: Maps
        list: true
      - name: externalMapUrl
        type: object
        label: External Map Url
        fields:
          - name: url
            type: text
            label: URL
            required: true
          - name: title
            type: text
            label: Title
            required: true
          - name: description
            type: rich-text
            label: Description
            required: true
  - name: approach
    label: Approach
    type: file
    path: src/approach.md
    fields:
      - name: title
        type: text
        label: Title
        required: true
      - name: content
        type: rich-text
        label: Content
        required: true
      - name: images
        type: image
        label: Images
        list: true
      - name: content2
        type: rich-text
        label: Content 2
        required: true
  - name: routes
    label: Routes
    type: collection
    path: src/routes
    fields:
      - name: id
        type: text
        label: ID
        required: true
        description: Will be sorted by id
      - name: published
        type: boolean
        label: Published
        required: true
      - name: slug
        type: text
        label: Slug
        required: true
        description: Small case, no spaces, no special characters
      - name: boulder
        type: text
        label: Boulder
        required: true
        description: Please use the defined boulder ID
      - name: zone
        type: number
        label: Zone
        required: true
        description: Please use the defined zone ID
      - name: name
        type: text
        label: Name
        required: true
      - name: rating
        type: number
        label: Rating
        required: true
        description: 0 - 3
      - name: description
        type: rich-text
        label: Description
      - name: gradings
        type: text
        label: Grading
        required: true
        description: Comma separated gradings, e.g. 1, 2, 3, project etc
      - name: image
        type: image
        label: Image
      - name: isSds
        type: boolean
        label: Is SDS
      - name: comment
        type: text
        label: Comment
  - name: boulders
    label: Boulders
    type: collection
    path: src/boulders
    fields:
      - name: id
        type: number
        label: ID
        required: true
      - name: published
        type: boolean
        label: Published
        required: true
      - name: order
        type: number
        label: Order
        required: true
      - name: slug
        type: text
        label: Slug
        required: true
        primary: true
      - name: name
        type: text
        label: Name
        required: true
      - name: zone
        type: number
        label: Zone
        description: Please use the defined zone ID
        required: true
      - name: image
        type: image
        label: Image
        description: Please use the signature image of the boulder
      - name: gps
        type: object
        label: GPS
        required: false
        fields:
          - name: lat
            type: number
            label: Latitude
          - name: lng
            type: number
            label: Longitude
      - name: access
        type: object
        label: Access
        required: false
        fields:
          - name: link
            type: text
            label: Link
          - name: text
            type: text
            label: Text
          - name: title
            type: text
            label: Title
          - name: target
            type: text
            label: Target
  - name: zones
    label: Zones
    type: collection
    path: src/zones
    fields:
      - name: id
        type: number
        label: ID
        required: true
        primary: true
      - name: order
        type: number
        label: Order
        required: true
      - name: name
        type: text
        label: Name
        required: true
      - name: published
        type: boolean
        label: Published
        required: true
      - name: access
        type: object
        label: Access
        required: false
        fields:
          - name: link
            type: text
            label: Link
          - name: text
            type: text
            label: Text
          - name: title
            type: text
            label: Title
          - name: target
            type: text
            label: Target
      