media:
  input: public/images
  output: /images
content:
  - name: landing
    label: Landing
    type: file
    path: src/landing.md
    fields:
      - name: title
        type: text
        label: Title
        required: true
      - name: content
        type: rich-text
        label: Content
        required: true
      - name: maps
        type: image
        label: Maps
        list: true
  - name: approach
    label: Approach
    type: file
    path: src/approach.md
    fields:
      - name: title
        type: text
        label: Title
        required: true
      - name: content
        type: rich-text
        label: Content
        required: true
      - name: images
        type: image
        label: Images
        list: true
      - name: content2
        type: rich-text
        label: Content 2
        required: true
      