media:
  input: public/images
  output: /images
content:
  - name: landing
    label: Landing
    type: file
    path: src/landing.md
    fields:
      - name: title
        type: text
        label: Title
        required: true
      - name: subtitle
        type: text
        label: Subtitle
        required: true
      - name: content
        type: rich-text
        label: Content
        required: true
      - name: mapUrl
        type: text
        label: Map URL
        required: true
      - name: maps
        type: image
        label: Maps
        list: true
      - name: externalMapUrl
        type: object
        label: External Map Url
        fields:
          - name: url
            type: text
            label: URL
            required: true
          - name: title
            type: text
            label: Title
            required: true
          - name: description
            type: rich-text
            label: Description
            required: true
  - name: approach
    label: Approach
    type: file
    path: src/approach.md
    fields:
      - name: title
        type: text
        label: Title
        required: true
      - name: content
        type: rich-text
        label: Content
        required: true
      - name: images
        type: image
        label: Images
        list: true
      - name: content2
        type: rich-text
        label: Content 2
        required: true
  - name: boulders
    label: Boulders
    type: collection
    path: src/boulders
    fields:
      - name: id
        type: number
        label: ID
        required: true
      - name: slug
        type: text
        label: Slug
        required: true
        primary: true
      - name: name
        type: text
        label: Name
        required: true
      - name: zone
        type: number
        label: Zone ( Please use the defined zone ID)
        required: true
  - name: zones
    label: Zones
    type: collection
    path: src/zones
    fields:
      - name: id
        type: number
        label: ID
        required: true
        primary: true
      - name: order
        type: number
        label: Order
        required: true
      - name: name
        type: text
        label: Name
        required: true
      - name: published
        type: boolean
        label: Published
        required: true
      - name: access
        type: object
        label: Access
        required: false
        fields:
          - name: link
            type: text
            label: Link
          - name: text
            type: text
            label: Text
          - name: title
            type: text
            label: Title
          - name: target
            type: text
            label: Target
      