media: public/images
content:
  - name: landing
    label: Landing
    type: file
    path: src/landing.md
    fields:
      - name: title
        type: text
        label: Title
        required: true
      - name: content
        type: rich-text
        label: Content
        required: true
      - name: maps
        type: image
        label: Maps
        list: true